languageCode: en-us
title: OpenShift Examples
theme: hugo-theme-learn
enableGitInfo: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    lineAnchors: ''
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    tabWidth: 2
taxonomies:
  category: categories
  tag: tags
  offlineSearch: true
params:
  themeVariant: gray
  editURL: 'https://github.com/openshift-examples/web/edit/master/content/'
  disableNextPrev: true
  custom_css:
    - '/css/highlight-default.css'
outputs:
  home:
    - HTML
    - RSS
    - JSON
Languages:
  en:
    menu:
      shortcuts:
        - name: <i class='fas fa-tags'></i> Tags
          url: /tags
          weight: 1
        - name: <i class='fab fa-fw fa-github'></i> openshift-examples/web
          identifier: github
          url: 'https://github.com/openshift-examples/web'
          weight: 10
        - name: <i class='fab fa-fw fa-twitter'></i> @RobertBohne
          identifier: twitter
          url: 'https://twitter.com/robertbohne'
          weight: 11
